"""
Integration tests for atomic background encounter batch processing.

These tests exercise the Python repository through the application's
database connection layer. They verify deterministic selection, committed
status and audit changes, complete rollback after failure, and usable
database resources after a failed transaction.
"""

from collections.abc import Iterator

import pytest

from api_service.database import (
    close_database_resources,
    get_connection,
    initialize_database_resources,
)
from api_service.database_timings import DatabasePhaseTimings
from api_service.repositories.encounter_batches import (
    BACKGROUND_CHANGE_SOURCE,
    BACKGROUND_REQUEST_METHOD,
    BACKGROUND_REQUEST_PATH,
    BACKGROUND_SERVICE_NAME,
    EncounterBatchProcessingError,
    process_scheduled_encounter_batch,
)


TEST_ENCOUNTER_IDS = (
    -8104,
    -8103,
    -8102,
    -8101,
)

TEST_WORKER_ID = "integration-background-worker"
SUCCESS_BATCH_ID = "integration-encounter-batch-success"
ROLLBACK_BATCH_ID = "integration-encounter-batch-rollback"


@pytest.fixture(scope="module", autouse=True)
def database_resources() -> Iterator[None]:
    """
    Initialize and verify database resources for this test module.

    Skip cleanly when PostgreSQL is unavailable. Opening a real connection
    is required because the connection-per-operation strategy does not open
    a connection during initialize_database_resources().
    """

    try:
        initialize_database_resources()

        with get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute("SELECT 1")
    except Exception as error:
        close_database_resources()

        pytest.skip(
            "PostgreSQL database resources are unavailable for this "
            f"integration test: {error}"
        )

    try:
        yield
    finally:
        close_database_resources()


def remove_test_encounters() -> None:
    """
    Remove all test encounter and audit records.

    Encounter rows are deleted first because the encounter trigger records
    DELETE operations. Audit rows are deleted second so cleanup leaves no
    audit records generated by the cleanup itself.
    """

    encounter_ids = list(TEST_ENCOUNTER_IDS)

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                DELETE FROM encounters
                WHERE encounter_id = ANY(%s::int[])
                """,
                (encounter_ids,),
            )

            cursor.execute(
                """
                DELETE FROM encounter_audit
                WHERE encounter_id = ANY(%s::int[])
                """,
                (encounter_ids,),
            )


def insert_scheduled_test_encounters() -> None:
    """Insert a deterministic set of scheduled encounters."""

    rows = [
        (
            encounter_id,
            1001,
            501,
            1,
            "2026-07-21",
            "background_batch_test",
            "scheduled",
        )
        for encounter_id in TEST_ENCOUNTER_IDS
    ]

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.executemany(
                """
                INSERT INTO encounters (
                    encounter_id,
                    patient_id,
                    provider_id,
                    facility_id,
                    encounter_date,
                    encounter_type,
                    status
                )
                VALUES (
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s
                )
                """,
                rows,
            )


@pytest.fixture
def scheduled_test_encounters() -> Iterator[tuple[int, ...]]:
    """Provide clean scheduled encounter rows for each test."""

    remove_test_encounters()

    try:
        insert_scheduled_test_encounters()
        yield TEST_ENCOUNTER_IDS
    finally:
        remove_test_encounters()


def read_test_encounter_statuses() -> dict[int, str]:
    """Return the persisted status of every test encounter."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    encounter_id,
                    status
                FROM encounters
                WHERE encounter_id = ANY(%s::int[])
                ORDER BY encounter_id
                """,
                (list(TEST_ENCOUNTER_IDS),),
            )

            rows = cursor.fetchall()

    return {
        row["encounter_id"]: row["status"]
        for row in rows
    }


def count_update_audits_for_batch(batch_id: str) -> int:
    """Count persisted UPDATE audit rows for one batch identifier."""

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT COUNT(*) AS audit_count
                FROM encounter_audit
                WHERE encounter_id = ANY(%s::int[])
                  AND operation_type = 'UPDATE'
                  AND request_id = %s
                """,
                (
                    list(TEST_ENCOUNTER_IDS),
                    batch_id,
                ),
            )

            row = cursor.fetchone()

    assert row is not None
    return row["audit_count"]


@pytest.mark.integration
def test_batch_commits_exact_encounters_and_correlated_audits(
    scheduled_test_encounters: tuple[int, ...],
) -> None:
    """
    Verify deterministic processing and committed audit evidence.

    The first three scheduled encounter IDs must be completed, while the
    fourth remains scheduled. One correlated UPDATE audit row must persist
    for each completed encounter.
    """

    expected_processed_ids = list(
        scheduled_test_encounters[:3]
    )

    timings = DatabasePhaseTimings()

    result = process_scheduled_encounter_batch(
        batch_size=3,
        worker_id=TEST_WORKER_ID,
        batch_id=SUCCESS_BATCH_ID,
        timings=timings,
    )

    assert result["batch_id"] == SUCCESS_BATCH_ID
    assert result["worker_id"] == TEST_WORKER_ID
    assert result["requested_batch_size"] == 3
    assert result["selected_count"] == 3
    assert result["updated_count"] == 3
    assert result["audit_count"] == 3
    assert result["encounter_ids"] == expected_processed_ids

    assert result["status_transition"] == {
        "from": "scheduled",
        "to": "completed",
    }

    assert len(result["audit_rows"]) == 3

    for audit_row in result["audit_rows"]:
        assert audit_row["operation_type"] == "UPDATE"
        assert audit_row["old_status"] == "scheduled"
        assert audit_row["new_status"] == "completed"
        assert audit_row["changed_by"] == TEST_WORKER_ID
        assert (
            audit_row["change_source"]
            == BACKGROUND_CHANGE_SOURCE
        )
        assert audit_row["request_id"] == SUCCESS_BATCH_ID
        assert (
            audit_row["request_method"]
            == BACKGROUND_REQUEST_METHOD
        )
        assert (
            audit_row["request_path"]
            == BACKGROUND_REQUEST_PATH
        )
        assert (
            audit_row["service_name"]
            == BACKGROUND_SERVICE_NAME
        )

    persisted_statuses = read_test_encounter_statuses()

    assert persisted_statuses == {
        TEST_ENCOUNTER_IDS[0]: "completed",
        TEST_ENCOUNTER_IDS[1]: "completed",
        TEST_ENCOUNTER_IDS[2]: "completed",
        TEST_ENCOUNTER_IDS[3]: "scheduled",
    }

    assert (
        count_update_audits_for_batch(SUCCESS_BATCH_ID)
        == 3
    )

    assert timings.query_ms > 0
    assert timings.fetch_ms >= 0
    assert timings.acquire_ms >= 0
    assert timings.release_ms >= 0
    assert timings.total_ms > 0

    assert (
        result["database_timings"]
        == timings.as_dict()
    )


@pytest.mark.integration
def test_batch_failure_rolls_back_all_changes_and_releases_connection(
    scheduled_test_encounters: tuple[int, ...],
) -> None:
    """
    Verify transaction rollback after an injected post-update failure.

    No status change or correlated UPDATE audit row may survive, and the
    database connection layer must remain usable after the rollback.
    """

    with pytest.raises(
        EncounterBatchProcessingError,
        match="Injected failure after encounter update",
    ):
        process_scheduled_encounter_batch(
            batch_size=2,
            worker_id=TEST_WORKER_ID,
            batch_id=ROLLBACK_BATCH_ID,
            inject_failure_after_update=True,
        )

    persisted_statuses = read_test_encounter_statuses()

    assert persisted_statuses == {
        encounter_id: "scheduled"
        for encounter_id in TEST_ENCOUNTER_IDS
    }

    assert (
        count_update_audits_for_batch(ROLLBACK_BATCH_ID)
        == 0
    )

    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 AS connection_reuse_check"
            )
            row = cursor.fetchone()

    assert row is not None
    assert row["connection_reuse_check"] == 1