"""
HTTP integration test for the background encounter batch endpoint.

The test creates isolated scheduled encounters through Docker PostgreSQL,
calls the running FastAPI service, and verifies the committed database and
audit results.
"""

import os
import subprocess
from collections.abc import Iterator
from pathlib import Path

import pytest
import requests


PROJECT_ROOT = Path(__file__).resolve().parents[2]

API_BASE_URL = os.getenv(
    "SDET_API_BASE_URL",
    "http://localhost:8000",
)

TEST_ENCOUNTER_IDS = (
    -8204,
    -8203,
    -8202,
    -8201,
)

TEST_WORKER_ID = "http-background-worker"


def run_psql(sql_text: str) -> subprocess.CompletedProcess[str]:
    """Run SQL against the Docker Compose PostgreSQL service."""

    return subprocess.run(
        [
            "docker",
            "compose",
            "exec",
            "-T",
            "postgres",
            "psql",
            "-U",
            "sdet_user",
            "-d",
            "sdet_reliability",
            "-v",
            "ON_ERROR_STOP=1",
            "-At",
        ],
        input=sql_text,
        text=True,
        capture_output=True,
        cwd=PROJECT_ROOT,
        check=False,
    )


def postgres_is_available() -> tuple[bool, str]:
    """Return whether the Docker PostgreSQL service is ready."""

    try:
        result = subprocess.run(
            [
                "docker",
                "compose",
                "exec",
                "-T",
                "postgres",
                "pg_isready",
                "-U",
                "sdet_user",
                "-d",
                "sdet_reliability",
            ],
            text=True,
            capture_output=True,
            cwd=PROJECT_ROOT,
            check=False,
        )
    except FileNotFoundError:
        return False, "Docker is unavailable"

    details = (
        result.stdout
        or result.stderr
        or "PostgreSQL is unavailable"
    ).strip()

    return result.returncode == 0, details


def remove_test_records() -> None:
    """
    Delete test encounters and all audit rows generated by cleanup.

    Encounters are deleted first because their DELETE trigger creates audit
    rows. Audit rows are removed afterward.
    """

    encounter_ids = ", ".join(
        str(encounter_id)
        for encounter_id in TEST_ENCOUNTER_IDS
    )

    result = run_psql(
        f"""
        DELETE FROM encounters
        WHERE encounter_id IN ({encounter_ids});

        DELETE FROM encounter_audit
        WHERE encounter_id IN ({encounter_ids});
        """
    )

    assert result.returncode == 0, (
        f"Cleanup failed.\n"
        f"STDOUT:\n{result.stdout}\n"
        f"STDERR:\n{result.stderr}"
    )


def insert_scheduled_test_records() -> None:
    """Insert deterministic scheduled encounters for the endpoint."""

    values = ",\n".join(
        (
            f"({encounter_id}, 1001, 501, 1, "
            f"'2026-07-21', "
            f"'background_endpoint_test', 'scheduled')"
        )
        for encounter_id in TEST_ENCOUNTER_IDS
    )

    result = run_psql(
        f"""
        INSERT INTO encounters (
            encounter_id,
            patient_id,
            provider_id,
            facility_id,
            encounter_date,
            encounter_type,
            status
        )
        VALUES
        {values};
        """
    )

    assert result.returncode == 0, (
        f"Test setup failed.\n"
        f"STDOUT:\n{result.stdout}\n"
        f"STDERR:\n{result.stderr}"
    )


@pytest.fixture
def scheduled_endpoint_encounters() -> Iterator[tuple[int, ...]]:
    """Provide isolated scheduled encounters for the HTTP test."""

    available, details = postgres_is_available()

    if not available:
        pytest.skip(
            "Docker PostgreSQL is unavailable for endpoint "
            f"integration testing: {details}"
        )

    remove_test_records()

    try:
        insert_scheduled_test_records()
        yield TEST_ENCOUNTER_IDS
    finally:
        remove_test_records()


@pytest.mark.integration
def test_background_encounter_batch_endpoint_commits_exact_batch(
    scheduled_endpoint_encounters: tuple[int, ...],
) -> None:
    """
    Verify that the running API processes the first three test encounters.

    The HTTP response, persisted encounter states, and PostgreSQL audit rows
    must agree on the exact processed IDs and correlation metadata.
    """

    endpoint = (
        f"{API_BASE_URL}/qa/background-encounter-batch"
        f"?batch_size=3"
        f"&worker_id={TEST_WORKER_ID}"
    )

    try:
        response = requests.post(
            endpoint,
            timeout=15,
        )
    except requests.RequestException as error:
        pytest.skip(
            "API stack is unavailable for background endpoint "
            f"validation: {error}"
        )

    if response.status_code == 404:
        pytest.skip(
            "Background encounter batch QA endpoint is disabled "
            "or unavailable"
        )

    assert response.status_code == 200, response.text

    payload = response.json()
    request_id = response.headers.get("x-request-id")

    expected_processed_ids = list(
        scheduled_endpoint_encounters[:3]
    )

    assert request_id
    assert payload["workload_type"] == (
        "background_encounter_batch"
    )
    assert payload["batch_id"] == request_id
    assert payload["worker_id"] == TEST_WORKER_ID
    assert payload["requested_batch_size"] == 3
    assert payload["selected_count"] == 3
    assert payload["updated_count"] == 3
    assert payload["audit_count"] == 3
    assert payload["encounter_ids"] == expected_processed_ids

    assert payload["status_transition"] == {
        "from": "scheduled",
        "to": "completed",
    }

    phases = payload["database_timings"]

    assert set(phases) == {
        "acquire_ms",
        "query_ms",
        "fetch_ms",
        "release_ms",
        "total_ms",
    }

    for value in phases.values():
        assert isinstance(value, (int, float))
        assert value >= 0

    encounter_ids = ", ".join(
        str(encounter_id)
        for encounter_id in TEST_ENCOUNTER_IDS
    )

    verification = run_psql(
        f"""
        SELECT
            encounter_id || '|' || status
        FROM encounters
        WHERE encounter_id IN ({encounter_ids})
        ORDER BY encounter_id;

        SELECT
            encounter_id || '|' ||
            operation_type || '|' ||
            old_status || '|' ||
            new_status || '|' ||
            changed_by || '|' ||
            change_source || '|' ||
            request_id
        FROM encounter_audit
        WHERE encounter_id IN ({encounter_ids})
          AND operation_type = 'UPDATE'
          AND request_id = '{request_id}'
        ORDER BY encounter_id;
        """
    )

    assert verification.returncode == 0, (
        f"Database verification failed.\n"
        f"STDOUT:\n{verification.stdout}\n"
        f"STDERR:\n{verification.stderr}"
    )

    lines = [
        line.strip()
        for line in verification.stdout.splitlines()
        if line.strip()
    ]

    status_lines = [
        line
        for line in lines
        if line.count("|") == 1
    ]

    audit_lines = [
        line
        for line in lines
        if line.count("|") == 6
    ]

    assert status_lines == [
        f"{TEST_ENCOUNTER_IDS[0]}|completed",
        f"{TEST_ENCOUNTER_IDS[1]}|completed",
        f"{TEST_ENCOUNTER_IDS[2]}|completed",
        f"{TEST_ENCOUNTER_IDS[3]}|scheduled",
    ]

    assert audit_lines == [
        (
            f"{encounter_id}|UPDATE|scheduled|completed|"
            f"{TEST_WORKER_ID}|background_workload|"
            f"{request_id}"
        )
        for encounter_id in expected_processed_ids
    ]